analyzer:
  errors:
    depend_on_referenced_packages: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore

include: package:flutter_lints/flutter.yaml

linter:
  rules:
