name: insoblok
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: any
  flutter_inappwebview: any
  cached_network_image: any
  flutter_svg: any
  shimmer: any
  animated_text_kit: any
  flutter_native_splash: any
  video_player: any
  chewie: any
  carousel_slider: any
  flutter_quill: any
  vsc_quill_delta_to_html: any
  flutter_html: any
  gradient_borders: any
  loading_indicator: any
  flutter_staggered_grid_view: any

  logger: any
  freezed_annotation: any
  json_annotation: any

  permission_handler: any
  fluttertoast: any
  get_ip_address: any
  image_picker: any

  fluro: any
  sqflite: any
  device_info_plus: any

  provider: any
  observable_ish: any
  get_it: any
  stacked: any

  url_launcher: any
  http: any
  share_plus: any
  app_links: any

  firebase_analytics: any
  cloud_firestore: any
  firebase_storage: any
  firebase_auth: any
  firebase_app_check: any

  dio: any
  path_provider: any
  # reown_appkit: ^1.4.3+1
  google_sign_in: any
  smooth_page_indicator: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: any
  freezed: any
  build_runner: any
  web3dart_builders: any

# dependency_overrides:
#   intl: ^0.20.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/fonts/
    - assets/data/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800

flutter_intl:
  main_locale: en_US
  enabled: true
